# This code has been made by itzCrih
name: CoralWinter
version: '${project.version}'
main: it.itzcrih.coralwinter.CoralWinter
authors: [itzCrih]
description: CoralMC Snowball fight plugin replica
softdepend: [ProtocolLib]
commands:
  coralwinter:
    description: Main command for CoralWinter plugin.
    usage: /coralwinter [reload|santashovel]
    aliases: [cw]