#   _________                     .__  __      __.__        __
#   \_   ___ \  ________________  |  |/  \    /  \__| _____/  |_  ___________
#   /    \  \/ /  _ \_  __ \__  \ |  |\   \/\/   /  |/    \   __\/ __ \_  __ \
#   \     \___(  <_> )  | \// __ \|  |_\        /|  |   |  \  | \  ___/|  | \/
#    \______  /\____/|__|  (____  /____/\__/\  / |__|___|  /__|  \___  >__|
#           \/                  \/           \/          \/          \/
# CoralWinter v1.5-SNAPSHOT by itzCrih
# https://github.com/itzCrih/CoralWinter

# Configuration
# Diamond shovel settings
santashovel:
  # Please select an item for santashovel. (default: DIAMOND_SPADE)
  type: DIAMOND_SPADE # Please insert a valid material (STONE_SPADE, GOLD_SPADE, DIAMOND_SPADE, WOOD_SPADE, IRON_SPADE)
  # Should we give santashovel whenever a player joins?
  give_on_join: true
  # Should we enable santashovel command?
  enable_command: true
  # Display name of the shovel
  display-name: "&c&lChristmas shovel"
  # Description of the shovel
  lore:
    - "&7Damn, the whole lobby is full of snow."
    - "&7I would definitely be happy if you clean it!"
    - "&7 "
    - "&7(Hold &bLeft-click &7to clean the snow)"
  # Should we enchant the shovel for a glow effect?
  enable_glow: true
  # Should we give Speed III and ability to fly when you hold your shovel?
  when_holding_enable_effects: true
  # What sound should we play whenever you break snow with your shovel?
  sound_when_breaking: NOTE_PIANO

# Block protection settings
block_protection:
  # If both enabled you will be able to break and place blocks if you have the following permission:
  # coralwinter.bypass.blockprotection
  block_place_enabled: true
  block_break_enabled: true

# Snow command settings
snow_command:
  # How many seconds should the particles stay near the player
  seconds: 10 # seconds
  # How many seconds should the cooldown of the command be
  cooldown: 30 # seconds

# Snowfall settings
snow_fall:
  # Should we enable this feature?
  enabled: true # [!] You need ProtocolLib to successfully run this feature